linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - nakedret
    - funlen
    - wsl
    - gocognit
    - gomnd
    - godox
    - goerr113
    - nlreturn
    - testpackage
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - errcheck
