version: 2
before:
  hooks:
    - go mod download
builds:
  - id: darwin
    main: ./cmd/putio-sync/main.go
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=1
  - id: linux_windows
    main: ./cmd/putio-sync/main.go
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - repository:
      owner: putdotio
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage:  https://github.com/putdotio/putio-sync
    description: Put.io folder sync app
    install: |
      bin.install "putio-sync"
    test: |
      system "#{bin}/putio-sync -version"
