before:
  hooks:
    - go mod download
builds:
  -
    main: ./cmd/putio-sync/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - tap:
      owner: putdotio
      name: homebrew-putio-sync
    folder: Formula
    homepage:  https://github.com/putdotio/putio-sync
    description: Put.io folder sync app
    install: |
      bin.install "putio-sync"
    test: |
      system "#{bin}/putio-sync -version"
