env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    ldflags:
    - -s -w -X main.Version={{.Version}}
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}"
    replacements:
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: putdotio
      name: homebrew-putio-sync
    folder: Formula
    homepage:  https://github.com/putdotio/putio-sync
    description: Put.io folder sync app
    install: |
      bin.install "putio-sync"
    test: |
      system "#{bin}/putio-sync -version"
