language: go
go: "1.15.x"
cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build
install: true
before_script:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
script:
- golangci-lint run
- go test -race ./...
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
